zuul:
  routes:
    greetings:
      path: /config1/**
      serviceId: CONFIGCLIENT
    greetingsConfig2:
      path: /config2/**
      serviceId: CONFIGCLIENT2

eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080   # HTTP (Tomcat) port